// traduzido por Weibson Santos -->
tinyMCE.addI18n('en.advanced',{
style_select:"Estilos",
font_size:"Tamanho",
fontdefault:"Tipo de fonte",
block:"Formatação",
paragraph:"Paragráfo",
div:"Div",
address:"Endereço",
pre:"Pré-formatado",
h1:"Título 1",
h2:"Título 2",
h3:"Título 3",
h4:"Título 4",
h5:"Título 5",
h6:"Título 6",
blockquote:"Citação em bloco",
code:"Código",
samp:"Amostra de código",
dt:"Termo da definição",
dd:"Descrição da definição",
bold_desc:"Negrito (Ctrl+B)",
italic_desc:"Itálico (Ctrl+I)",
underline_desc:"Sublinhado (Ctrl+U)",
striketrough_desc:"Riscado",
justifyleft_desc:"Alinhar à esquerda",
justifycenter_desc:"Centralizar",
justifyright_desc:"Alinhar à direita",
justifyfull_desc:"Justificar",
bullist_desc:"Marcadores",
numlist_desc:"Numeradores",
outdent_desc:"Diminuir avanço",
indent_desc:"Aumentar avanço",
undo_desc:"Desfazer (Ctrl+Z)",
redo_desc:"Refazer (Ctrl+Y)",
link_desc:"Inserir/editar hyperlink",
unlink_desc:"Remover hyperlink",
image_desc:"Inserir/editar imagem",
cleanup_desc:"Limpar código incorreto",
code_desc:"Editar código fonte",
sub_desc:"Inferior à linha",
sup_desc:"Superior à linha",
hr_desc:"Inserir separador horizontal",
removeformat_desc:"Remover formatação",
custom1_desc:"Insira aqui a sua descrição personalizada",
forecolor_desc:"Selecionar a cor do texto",
backcolor_desc:"Selecionar a cor de fundo",
charmap_desc:"Inserir caracteres especiais",
visualaid_desc:"Alternar guias/elementos invisíveis",
anchor_desc:"Inserir/editar âncora",
cut_desc:"Cortar",
copy_desc:"Copiar",
paste_desc:"Colar",
image_props_desc:"Propriedades da imagem",
newdocument_desc:"Novo documento",
help_desc:"Ajuda",
blockquote_desc:"Citação em bloco",
clipboard_msg:"Copiar/cortar/colar não está disponível no Mozilla e Firefox. Deseja mais informações sobre este problema?",
path:"Endereço",
newdocument:"Tem a certeza que deseja apagar tudo?",
toolbar_focus:"Ir para as ferramentas - Alt+Q, Ir para o editor - Alt-Z, Ir para o endereço do elemento - Alt-X",
more_colors:"Mais cores"
});