tinyMCE.addI18n('en.media_dlg',{
title:"Inserir/Editar mídia incorporada",
general:"Geral",
advanced:"Avançado",
file:"Arquivo/URL",
list:"Lista",
size:"Dimensões",
preview:"Preview",
constrain_proportions:"Manter proporções",
type:"Tipo",
id:"Id",
name:"Nome",
class_name:"Classe",
vspace:"Espaço vertical",
hspace:"Espaço horizontal",
play:"Execução automática",
loop:"Repetição automática",
menu:"Mostrar menu",
quality:"Qualidade",
scale:"Escala",
align:"Alinhamento",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Fundo",
base:"Base",
flashvars:"Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Oculto",
controller:"Controlador",
kioskmode:"Modo Quiosque",
playeveryframe:"Executar todas as frames",
targetcache:"Cache alvo",
correction:"Sem correcções",
enablejavascript:"Disponibilizar javaScript",
starttime:"Hora de início",
endtime:"Hora do fim",
href:"Href",
qtsrcchokespeed:"Choke speed",
target:"Alvo",
volume:"Volume",
autostart:"Execução automática",
enabled:"Ativado",
fullscreen:"Tela inteira",
invokeurls:"Invocar URLs",
mute:"Mudo",
stretchtofit:"Estender",
windowlessvideo:"Vídeo sem janela",
balance:"Stereo",
baseurl:"Base URL",
captioningid:"Id de legenda",
currentmarker:"Marcador atual",
currentposition:"Posição atual",
defaultframe:"Frame padrão",
playcount:"Play count",
rate:"Rate",
uimode:"UI Mode",
flash_options:"Opções Flash",
qt_options:"Opções Quicktime",
wmp_options:"Opções Windows Media Player",
rmp_options:"Opções Real Media Player",
shockwave_options:"Opções Shockwave",
autogotourl:"Auto goto URL",
center:"Centro",
imagestatus:"Status da imagem",
maintainaspect:"Manter aspecto",
nojava:"No java",
prefetch:"Prefetch",
shuffle:"Shuffle",
console:"Console",
numloop:"Num loops",
controls:"Controles",
scriptcallbacks:"callbacks de script",
swstretchstyle:"Stretch style",
swstretchhalign:"Stretch H-Align",
swstretchvalign:"Stretch V-Align",
sound:"Som",
progress:"Progresso",
qtsrc:"QT Src",
qt_stream_warn:"Fluxos de recursos rtsp devem ser acrescentados ao campo QT Src no Modo Avançado.\Numa versão sem fluxo também deve ser acrescentada ao campo Src.",
align_top:"Topo",
align_right:"Direita",
align_bottom:"Abaixo",
align_left:"Esquerda",
align_center:"Centro",
align_top_left:"Topo esquerda",
align_top_right:"Topo direita",
align_bottom_left:"Abaixo esquerda",
align_bottom_right:"Abaixo direita",
flv_options:"Opções de Flash video",
flv_scalemode:"Modo escala",
flv_buffer:"Buffer",
flv_startimage:"Imagem inicial",
flv_starttime:"Hora inicial",
flv_defaultvolume:"Volume padrão",
flv_hiddengui:"Hidden GUI",
flv_autostart:"Execução Automática",
flv_loop:"Loop",
flv_showscalemodes:"Mostrar modos escala",
flv_smoothvideo:"Smooth video",
flv_jscallback:"JS Callback"
});