tinyMCE.addI18n('en.advimage_dlg',{
tab_general:"Geral",
tab_appearance:"Aparência",
tab_advanced:"Avançado",
general:"Geral",
title:"Título",
preview:"Pré-Visualização",
constrain_proportions:"Manter proporções",
langdir:"Direção do texto",
langcode:"Código de idioma",
long_desc:"Descrição extensa",
style:"Estilo",
classes:"Classes",
ltr:"Da esquerda para a direita",
rtl:"Da direita para a esquerda",
id:"Id",
map:"Mapa de imagem",
swap_image:"Trocar imagem",
alt_image:"Imagem alternativa",
mouseover:"mouseover",
mouseout:"mouseout",
misc:"Misto",
example_img:"Pré-Visualização",
missing_alt:"Tem certeza que deseja continuar sem acrescentar uma descrição à imagem? (Isto pode gerar problemas de acessibilidade em alguns navegadores)",
dialog_title:"Inserir/editar imagem",
src:"Endereço da imagem",
alt:"Descrição da imagem",
list:"Lista de imagens",
border:"Limite",
dimensions:"Dimensões",
vspace:"Espaço vertical",
hspace:"Espaço horizontal",
align:"Alinhamento",
align_baseline:"Sobre a linha de texto",
align_top:"Topo",
align_middle:"Meio",
align_bottom:"Abaixo",
align_texttop:"Topo do texto",
align_textbottom:"Base do texto",
align_left:"Esquerda",
align_right:"Direita",
image_list:"Lista de imagens"
});