tinyMCE.addI18n('en.advlink_dlg',{
title:"Inserir/editar hyperlink",
url:"URL do hyperlink",
target:"Alvo",
titlefield:"Título",
is_email:"A URL digitada parece ser um endereço de e-mail. Deseja acrescentar o prefixo necessário mailto:?",
is_external:"A URL digitada parece conduzir a um link externo. Deseja acrescentar o prefixo necessário http://?",
list:"Lista de hyperlinks",
general_tab:"Geral",
popup_tab:"Popup",
events_tab:"Eventos",
advanced_tab:"Avançado",
general_props:"Propriedades gerais",
popup_props:"Propriedades de popup",
event_props:"Eventos",
advanced_props:"Propriedades avançadas",
popup_opts:"Opções",
anchor_names:"Âncoras",
target_same:"Abrir nesta janela/quadro",
target_parent:"Abrir na janela/quadro pai",
target_top:"Abrir na página inteira (substitui todos os quadros)",
target_blank:"Abrir numa nova janela",
popup:"Popup javascript",
popup_url:"URL do popup",
popup_name:"Nome da janela",
popup_return:"Inserir 'return false'",
popup_scrollbars:"Mostrar as barras de scroll",
popup_statusbar:"Mostrar a barra de status",
popup_toolbar:"Mostrar a barra de ferramentas",
popup_menubar:"Mostrar a barra de menu",
popup_location:"Mostrar a barra de endereços",
popup_resizable:"Permitir alteração do tamanho da janela",
popup_dependent:"Dependente (Mozilla/Firefox apenas)",
popup_size:"Tamanho",
popup_position:"Posição (X/Y)",
id:"Id",
style:"Estilo",
classes:"Classes",
target_name:"Nome do alvo",
langdir:"Direção do texto",
target_langcode:"Idioma alvo",
langcode:"Código da idioma",
encoding:"Codificação de caracteres",
mime:"Tipo MIME alvo",
rel:"Relação página/alvo",
rev:"Relação alvo/página",
tabindex:"Tabindex",
accesskey:"Chave de acesso",
ltr:"Da esquerda para a direita",
rtl:"Da direita para a esquerda",
link_list:"Lista de hyperlinks"
});